name: StatExport
version: '${project.version}'
main: de.benikum.statexport.Main
api-version: '1.20'
commands:
  statexport:
    usage: /statexport <add/remove/export>
  statleaderboard:
    usage: /statleaderboard <stat>